-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: 26 Nov 2016 pada 06.53
-- Versi Server: 10.1.13-MariaDB
-- PHP Version: 7.0.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ciaddressimport`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `tblayanan`
--

CREATE TABLE `tblayanan` (
  `id_layanan` int(5) NOT NULL,
  `nama_layanan` text NOT NULL,
  `dasar_hukum` text NOT NULL,
  `persyaratan` text NOT NULL,
  `jangka_waktu` text NOT NULL,
  `tarif` text NOT NULL,
  `masa_berlaku` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `tblayanan`
--

INSERT INTO `tblayanan` (`id_layanan`, `nama_layanan`, `dasar_hukum`, `persyaratan`, `jangka_waktu`, `tarif`, `masa_berlaku`) VALUES
(1, 'Izin Persetujuan Prinsip\n', 'Peraturan Daerah Nomor 84 Tahun 2004 tentang Persetujuan Prinsip di Kabupaten Lumajang', 'Mengisi formulir permohonan yang telah disediakan ditandatangani oleh pemohon dan oleh pejabat Lurah/Kepala Desa dan Camat setempat, dilampiri persyaratan : <ul><li>a. Fotocopy KTP pemohon</li> <li>b. Fotocopy Status tanah</li> <li>c. Akta Pendirian Perusahaan (kecuali Perorangan)</li> <li>d.	Gambar lokasi / tanah yang dimohon</li> <li>e. Uraian rencana proyek yang akan dibangun</li></ul>', '7 + ( Proses tindak lanjut dari Pemerintah Kabupaten Lumajang )', 'Non Retribusi', '1 tahun'),
(2, 'Izin Lokasi', 'Keputusan Bupati Kepala Daerah TK II Lumajang No. 347 Tahun 1999 tentang Tata Cara Pemberian Izin Lokasi', 'Mengisi formulir permohonan yang telah disediakan ditandatangani oleh pemohon dan oleh pejabat Lurah/Kepala Desa dan Camat setempat, dilampiri persyaratan : <ul><li>a. Fotocopy KTP pemohon</li> <li>b. Fotocopy Status tanah</li> <li>c. Akta Pendirian Perusahaan (kecuali Perorangan)</li> <li>d.	Gambar lokasi / tanah yang dimohon</li> <li>e. Uraian rencana proyek yang akan dibangun</li></ul>', '7 + ( Proses tindak lanjut dari Pemerintah Kabupaten Lumajang )', 'Non Retribusi', '1 tahun'),
(3, 'Izin Mendirikan Bangunan (IMB)', 'Peraturan Daerah Nomor 15 Tahun 2011 tentang Retribusi Izin Mendirikan Bangunan', 'Mengisi formulir permohonan yang telah disediakan ditandatangani oleh pemohon dan oleh pejabat Lurah / Kepala Desa dan Camat setempat, dilampiri persyaratan : <ul><li>a. Fotocopy KTP pemohon</li> <li>b. Fotocopy Status tanah</li> <li>c. Gambar Teknis Konstruksi</li> <li>d. Gambar lokasi / tanah yang dimohon</li> <li>e. d.	Sondir ( untuk tower & bangunan bertingkat > 2 lantai )</li></ul> Tambahan persyaratan untuk bangunan bertingkat pergudangan / usaha : <br>  <ul><li>a. Perhitungan konstruksi beton atau perhitungan konstruksi baja. Tambahan persyaratan untuk usaha/industri </li><li>b. Fotokopi akta pendirian perusahaan</li><li>c. Fotokopi NPWP</li><li>d. Fotokopi Persetujuan Prinsip dan atau Izin / Klasifikasi baja</li><li>Fotokopi Izin lokasi</li></ul> Tambahan persyaratan untuk Tower : <ul><li>a. Sondhir / analisa struktur tanah</li><li>b. Perhitungan kontruksi beton / baja</li></ul>', '7 + x hari <br> X hari =  <br> <ul><li>1. Pembayaran atau pelunasan retribusi</li><li>2.Kesesuaian berkas dengan data lapangan</li><li> 3. Proses tindaklanjut dari Instansi terkait</li></ul>', 'Terlampir', 'Selamanya selama tidak ada perubahan'),
(4, 'Izin Gangguan (HO)', 'Peraturan Daerah Nomor 16 Tahun 2011 tentang Retribusi Izin Gangguan', 'Mengisi formulir permohonan yang telah disediakan ditandatangani oleh pemohon dan oleh pejabat Lurah/Kepala Desa dan Camat setempat,  dilampiri persyaratan:<br> <ul> <li>Formulir permohonan</li> <li>Fotokopi KTP Pemohon</li> <li>Fotokopi IMB</li> <li>Fotokopi Status Tanah / Hak AtasTanah</li> <li>Akta Pendirian Perusahaan ( kecuali perorangan )</li> <li>Pas Photo berwarna terbaru 4 x 6 ( 2 lembar)</li> <li>BPJS Ketenagakerjaan</li> <li>Dokumen Lingkungan Hidup</li> </ul>', '7 + x hari <br> X hari =  <br> <ul><li>1. Pembayaran atau pelunasan retribusi</li><li>2.Kesesuaian berkas dengan data lapangan</li><li> 3. Proses tindaklanjut dari Instansi terkait</li></ul>', 'Terlampir', 'Selama perusahaan melakukan usahanya'),
(5, 'Surat Izin Usaha Perdagangan (SIUP)', 'Peraturan Daerah Nomor 10 Tahun 2002 tentang Surat Ijin Usaha Perdagangan', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Pas Foto warna terbaru 4 x 6 (2 lembar)</li> </ul>', '3 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '5 tahun'),
(6, 'Tanda Daftar Perusahaan (TDP)', 'Peraturan Daerah Nomor 54 Tahun 2002 tentang Tanda Daftar Perusahaan', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Susunan Pengurus (bila Koperasi)</li> </ul>', '2 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '5 tahun'),
(7, 'Tanda Daftar Gudang (TDG) \r\n', 'Peraturan Daerah Nomor 3 Tahun 2002 tentang Tanda Daftar Gudang', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotokopi KTP</li> <li>Fotocopy NPWP</li> <li>Fotokopi IMB, HO, SIUP, TDP </li> <li>Fotokopi Perjanjian Sewa Menyewa / Penguasaan Gudang (bila Sewa)</li> </ul>', '3 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '5 tahun'),
(8, 'Tanda Daftar Industri (TDI) \r\n', 'Peraturan Daerah Nomor 27 Tahun 2004 tentang Surat Ijin Industri, Ijin Perluasan, dan Tanda Daftar Industri', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotokopi KTP</li> <li>Fotocopy NPWP</li> <li>Fotokopi IMB / Surat Perjanjian Sewa Menyewa (bila Sewa)</li> <li>Fotokopi HO, SIUP, TDP </li> <li>Akta Pendirian Perusahaan ( kecuali perorangan)</li> </ul> <br> TDI diajukan untuk Perusahaan yang Modal Investasi Mesin sampai dengan Rp. 200.000.000,-', '3 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '5 tahun'),
(9, 'Surat Izin Usaha Industri (SIUI)\r\n', 'Peraturan Daerah Nomor 27 Tahun 2004 tentang Surat Ijin Industri, Ijin Perluasan, dan Tanda Daftar Industri', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotokopi KTP</li> <li>Fotocopy NPWP</li> <li>Fotokopi IMB / Surat Perjanjian Sewa Menyewa (bila Sewa)</li> <li>Fotokopi HO, SIUP, TDP </li> <li>Akta Pendirian Perusahaan ( kecuali perorangan)</li> </ul> SIUI diajukan untuk Perusahaan yang Modal Investasi Mesin lebih dari Rp. 200.000.000,-', '5 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '5 tahun'),
(10, 'Izin Usaha Penggilingan Padi (HULLER)\r\n', 'Peraturan Daerah Nomor 14 Tahun 1990 tentang Perubahan Pertama Peraturan Daerah No. 17 Tahun 1981 tentang Usaha Penggilingan Padi, Huller dan Penyosohan Beras', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan:  <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Fotokopi IMB / Surat Perjanjian Sewa Menyewa (bila Sewa)</li> <li>Fotokopi HO, SIUP, TDP </li> <li>Akta Pendirian Perusahaan ( kecuali perorangan)</li> <li>Pas foto berwarna terbaru 4 x 6 (2 lembar)</li> <ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '5 tahun'),
(11, 'Izin Usaha Bengkel Roda 2 & 4\r\n', 'Peraturan Daerah Nomor 53 Tahun 2002 tentang Retribusi Ijin Usaha Bengkel Umum Kendaraan Bermotor', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Fotokopi IMB / Surat Perjanjian Sewa Menyewa (bila Sewa)</li> <li>Fotokopi HO, SIUP, TDP </li> <li>Akta Pendirian Perusahaan ( kecuali perorangan)</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '5 tahun'),
(12, 'Izin Usaha Rekreasi Dan Hiburan Umum (RHU)', 'Peraturan Daerah Nomor 12 Tahun 2002 tentang Ijin Usaha Rekreasi dan Hiburan Umum', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotokopi KTP</li> <li>Fotokopi  Akte Pendirian Perusahaan (kecuali perorangan)</li> <li>Fotokopi  HO</li> </ul>', '2 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '1 tahun'),
(13, 'Izin Usaha Rumah Makan (IRM)', 'Peraturan Daerah Nomor 13 Tahun 2002 tentang Ijin Usaha Rumah Makan', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Fotokopi IMB / Surat Perjanjian Sewa Menyewa (bila Sewa)</li> <li>Fotokopi HO, SIUP, TDP </li> <li>Akta Pendirian Perusahaan ( kecuali perorangan)</li>  </ul>', '2 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '3 tahun'),
(14, 'Izin Usaha Hotel Dengan Tanda Bunga Melati', 'Peraturan Daerah Nomor 14 Tahun 2002 tentang Ijin Usaha Hotel dengan Tanda Bunga Melati', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotokopi IMB / Surat Perjanjian Sewa Menyewa (bila Sewa)</li> <li>Fotokopi HO, SIUP, TDP </li> <li>Akta Pendirian Perusahaan ( kecuali perorangan)</li> </ul>', '2 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', '3 tahun'),
(15, 'Izin Pemasangan Reklame (IPR)', 'Peraturan Daerah Nomor  4 Tahun 2011 tentang Pajak Daerah', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Gambar desain dan kontruksi (khusus untuk yg menengah dan besar)</li> <li>Gambar situasi dan foto lokasi (khusus untuk yg menengah dan besar)</li> <li>Gambar Materi</li> </ul> (Membawa materi untuk diberi legalitas oleh KPT)', '7 hari kerja setelah berkas lengkap dan benar', 'Non Retribusi', 'Min. 1 Bulan & Max. 1 Tahun'),
(16, 'Pemakaian Kekayaan Daerah Untuk Reklame (PKDR)', 'Peraturan Daerah Nomor  8 Tahun 2012 tentang Retribusi Pemakaian Kekayaan Daerah', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Gambar desain dan kontruksi (khusus untuk yg menengah dan besar)</li> <li>Gambar situasi dan foto lokasi (khusus untuk yg menengah dan besar)</li> <li>Gambar Materi</li> <li>(Membawa materi untuk diberi legalitas oleh KPT)</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Reklame Papan / Billboard : Rp. 7.500,- /m²/bulan <br> Reklame Kain / Spanduk    : Rp. 5.000,- /m²/bulan', '1 Tahun'),
(17, 'Pemakaian Kekayaan Daerah Milik Dinas Pekerjaan Umum (PKDPU)', 'Peraturan Daerah Nomor  8 Tahun 2012 tentang Retribusi Pemakaian Kekayaan Daerah', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', '<ul> <li>Rumah Permanen : Rp. 7.500,- /m²/tahun</li> <li>Rumah Semi Permanen : Rp. 1.000,- /m²/tahun</li> <li>Rumah Sederhana : Rp. 500,- /m²/tahun</li> <li>Pembuatan jembatan diatas saluran : Rp. 2.500,- /m²/tahun</li> </ul>', '1 Tahun'),
(18, 'Pemakaian Kekayaan Daerah Tanah Permanen / Tidak Permanen (PKDP)', 'Peraturan Daerah Nomor  8 Tahun 2012 tentang Retribusi Pemakaian Kekayaan Daerah ', 'Mengisi formulir permohonan yang telah disediakan ditanda tangani oleh pemohon bermaterai dilampiri persyaratan: <br> <ul> <li>Fotocopy KTP pemohon</li> <li>Gambar Lokasi dan situasi</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', '<ul> <li>Pemakaian Tanah Permanen : Rp.500,- /m²/bulan</li> <li>Pemakaian Tanah Non Permanen : Rp.5.000,- /m² (sekali pakai)</li> </ul>', '1 Tahun'),
(19, 'Izin Usaha Pertambangan (IUP)', '<ul><li>a. Peraturan Daerah Nomor  18 Tahun 2006 tentang Surat Ijin Pertambangan Daerah</li><li> b. Peraturan Bupati Nomor 01 Tahun 2011 tentang Pengelolaan Pertambangan Mineral di Kabupaten Lumajang</li></ul>', 'Terlampir', '7 + x hari setelah berkas lengkap dan benar <br> X hari : Survei Tim Pokja Pertambangan', 'Non retribusi', 'Sesuai Rekom Tim Pokja Pertambangan'),
(20, 'SIPA ( SURAT IZIN PEMANFAATAN AIR BAWAH TANAH DAN AIR PERMUKAAN)', 'Peraturan Daerah Nomor  29 tahun 2004 tentang Ijin Pemanfaatan Air Bawah Tanah dan Air Permukaan', 'Terlampir', '7 + x hari setelah berkas lengkap dan benar<br> X hari :  <ul> <li>Survei Tim Pokja SIPA</li> <li>Rekomendasi P2T Propinsi Jawa Timur</li> </ul>', 'Non retribusi', 'Sesuai Rekomendasi P2T Propinsi Jawa Timur'),
(21, 'IZIN KLINIK', 'Peraturan Bupati Lumajang Nomor 23 Tahun 2012 Perizinan Klinik di Kabupaten Lumajang', '<ul> <li>Foto copy akte badan hukum dari notaris.</li> <li>Tanda daftar Dinas Sosial (untuk yayasan).</li> <li>Foto copy IMB.</li> <li>Foto copy ijin gangguan / HO.</li> <li>Foto copy sertifikat tanah atau surat persetujuan pemilik bangunan bagi yang mengontrak minimal 2 (dua) tahun.</li> <li>Surat pernyataan dari dokter penanggung jawab.</li> <li>Surat pernyataan dokter penanggung jawab tidak terikat dengan instansi lain (pemerintah / swasta) dan apabila merangkap di instansi lain harus ada dokter pengganti selama jam buka  pelayanan.</li> <li>Rekomendasi puskesmas </li> <li>Bagan struktur organisasi.</li> <li>Daftar ketenagaan</li> <li>Tenaga medis (termasuk dokter penanggungjawab)</li> <li>Tenaga paramedis</li> <li>Tenaga administrasi</li> <li>Tenaga lain</li> <li>Fotokopi SIP atau SIK bagi tenaga medis </li> <li>Denah situasi lokasi.</li> <li>Denah ruangan.</li> <li>Daftar perlengkapan medis dan non medis</li> <li>Daftar perlengkapan penunjang administrasi.</li> <li>Daftar  ariff pelayanan.</li> <li>Rencana dan jadual kegiatan.</li> <li>Foto copy izin yang sudah akan habis masa berlakunya (bagi perpanjangan).</li> </ul>', '7 + x hari setelah berkas lengkap dan benar <br> X hari : Tindak Lanjut PemKab Lumajang', 'Non retribusi', '5 Tahun'),
(22, 'IZIN RUMAH SAKIT', 'Peraturan Bupati Lumajang Nomor 22 Tahun 2012 tentang Perizinan Rumah Sakit', '<ul> <li>studi kelayakan</li> <li>master plan</li> <li>status kepemilikan; <li>rekomendasi izin mendirikan</li> <li>izin undang-undang gangguan (HO)</li> <li>persyaratan pengolahan limbah</li> <li>luas tanah dan sertifikatnya</li> <li>penamaan</li> <li>Izin Mendirikan Bangunan (IMB)</li> <li>Izin Penggunaan Bangunan (IPB)</li> <li>Izin Gangguan (HO)</li> </ul>', '7 + x hari setelah berkas lengkap dan benar <br> X hari : Tindak Lanjut PemKab Lumajang', 'Non retribusi', '2 Tahun Izin Mendirikan <br> 1 Tahun Izin Operasional Sementara'),
(23, 'TANDA DAFTAR USAHA JASA PERJALANAN WISATA', 'Peraturan Bupati Lumajang Nomor 40 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Jasa Perjalanan Wisata', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(24, 'TANDA DAFTAR USAHA PENYEDIAAN AKOMODASI', 'Peraturan Bupati Lumajang Nomor 41 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Penyediaan Akomodasi', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> <li>Surat Keterangan tentang Kapasitas penyediaan akomodais dan fasilitas yang tersedia</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(25, 'TANDA DAFTAR USAHA JASA MAKANAN DAN MINUMAN', 'Peraturan Bupati Lumajang Nomor 42 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Jasa Makanan dan Minuman', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> <li>Surat Keterangan tentang Kapasitas penyediaan jasa makanan dan minuman</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(26, 'TANDA DAFTAR USAHA KAWASAN PARIWISATA', 'Peraturan Bupati Lumajang Nomor 43 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Kawasan Pariwisata', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Fotokopi Bukti hak atas tanah</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(27, 'TANDA DAFTAR USAHA DAYA TARIK WISATA', 'Peraturan Bupati Lumajang Nomor 48 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Daya Tarik Wisata', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Fotokopi Bukti hak atas tanah</li> <li>Fotokopi bukti hak pengelolaan dari pemilik daya tarik wisata</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> <ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(28, 'TANDA DAFTAR USAHA PENYELENGGARAAN HIBURAN DAN REKREASI', 'Peraturan Bupati Lumajang Nomor 49 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Penyelenggaraan Hiburan dan Rekreasi', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(29, 'TANDA DAFTAR USAHA WISATA TIRTA', 'Peraturan Bupati Lumajang Nomor 50 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Wisata Tirta', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(30, 'TANDA DAFTAR USAHA JASA INFORMASI PARIWISATA', 'Peraturan Bupati Lumajang Nomor 51 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Jasa Informasi Pariwisata', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Fotokopi Bukti hak atas tanah</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(31, 'TANDA DAFTAR USAHA SPA', 'Peraturan Bupati Lumajang Nomor 52 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Spa', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Fotokopi Bukti hak atas tanah</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(32, 'TANDA DAFTAR USAHA JASA KONSULTAN PARIWISATA', 'Peraturan Bupati Lumajang Nomor 53 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Jasa Konsultan Pariwisata', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Fotokopi Bukti hak atas tanah</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(33, 'TANDA DAFTAR USAHA PENYELENGGARAAN PERTEMUAN, PERJALANAN INSENTIF, KONFERENSI DAN PAMERAN', 'Peraturan Bupati Lumajang Nomor 54 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Penyelenggaraan Pertemuan, Perjalanan Insentif, Konferensi dan Pameran', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(34, 'TANDA DAFTAR USAHA JASA PRAMUWISATA', 'Peraturan Bupati Lumajang Nomor 55 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Jasa Pramuwisata', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Fotokopi Bukti hak atas tanah</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi'),
(35, 'TANDA DAFTAR USAHA JASA TRANSPORTASI WISATA', 'Peraturan Bupati Lumajang Nomor 57 Tahun 2014 tentang Tata Cara Pendaftaran Usaha Jasa Transportasi Wisata', '<ul> <li>Fotocopy KTP pemohon</li> <li>Fotocopy NPWP</li> <li>Fotocopy Akta Pendirian Perusahaan (bila berbadan hukum)</li> <li>Fotocopy Pengesahan Badan Hukum (bila berbadan hukum)</li> <li>Fotokopi SK Penunjukkan Pimpinan Cabang (bila cabang)</li> <li>Fotokopi Bukti hak atas tanah</li> <li>Dokumen Lingkungan Hidup</li> <li>Fotokopi Izin Teknis dari Dinas Kebudayaan dan Pariwisata</li> <li>Surat Pernyataan tentang perkiraan kapasitas jasa transportasi wisata</li> </ul>', '5 hari kerja setelah berkas lengkap dan benar', 'Non retribusi', 'Selama usaha pariwisata tidak terjadi perubahan kondisi');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tblayanan`
--
ALTER TABLE `tblayanan`
  ADD PRIMARY KEY (`id_layanan`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tblayanan`
--
ALTER TABLE `tblayanan`
  MODIFY `id_layanan` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=57;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
